# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: '3.4'
services:
  orgviewer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      GLOBAL_API_URL: http://localhost:8083
      # VUE_APP_THEME_CSS: "frederikshavn.custom.css"
      # GLOBAL_API_ROOT_UUID: "f06ee470-9f17-566f-acbe-e938112d46d9"
      # Loenorganisation
      GLOBAL_API_ROOT_UUID: "fb2d158f-114e-5f67-8365-2c520cf10b58"
      # CUSTOMER: frederikshavn-med

      # Required for SAML proxy-pass
      # GLOBAL_API_URL should point to ourselves
      SAML_TOKEN: "291036bf-df89-48ae-b6e4-119d32a2729a"
      PROXY_PASS_TO: http://mo:5000
    ports:
      - "8083:80"
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external:
      name: "os2mo_default"
