# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: '3.4'
services:
  orgviewer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      GLOBAL_API_URL: http://192.168.1.225:5001
      # GLOBAL_API_URL: http://localhost:8083
      # GLOBAL_APP_TITLE: "Orgviewer demo"
      # VUE_APP_THEME_CSS: "frederikshavn.custom.css"
      # VUE_APP_TREE_LAYOUT: "hybrid"
      # VUE_APP_LOGO_PATH: "https://frederikshavn.dk/Resources/images/frk_logo_blue.svg"
      # VUE_APP_FAVICON_PATH: "https://frederikshavn.dk/Resources/images/favicon.ico"

      GLOBAL_API_ROOT_UUID: "f06ee470-9f17-566f-acbe-e938112d46d9"
      # Loenorganisation
      # GLOBAL_API_ROOT_UUID: "fb2d158f-114e-5f67-8365-2c520cf10b58"

      # CUSTOMER: frederikshavn-med

      # Required for Keycloak auth
      # GLOBAL_API_URL should point to ourselves
      KEYCLOAK_CLIENT_SECRET: "30303030-3030-3030-3030-303030303030"
      PROXY_PASS_TO: http://mo:5000
    ports:
      - "8083:80"
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external:
      name: "os2mo_default"
